version: '3.7'

services:

#  reverse-proxy:
#    image: traefik:v2.0
#    ports:
#      - "80:80"
#      - "9090:8080" # The Web UI
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./etc/infrastructure/traefik/traefik.yml:/etc/traefik/traefik.yml

  app:
    build:
      context: .
      target: php_build
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/srv:rw
      - ./etc/infrastructure/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.ini

  gateway:
    build:
      context: .
      dockerfile: ./etc/infrastructure/nginx/Dockerfile
    depends_on:
      - app
    environment:
      APP_ROOT: /srv/app/public
      PHP_UPSTREAM: app
    ports:
      - target: 80
        published: 8080
    volumes:
      - ./app/public:/srv/app/public:rw
      - ./etc/infrastructure/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./etc/infrastructure/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    labels:
      - traefik.http.routers.app-symfony.rule=PathPrefix(`/sf`,`/sf/`)
      - traefik.http.routers.app-symfony.middlewares=app-symfony@docker
      - traefik.http.middlewares.app-symfony.stripprefix.prefixes=/sf,/sf/,
      - traefik.http.middlewares.app-symfony.stripprefix.forceslash=false

  db:
    image: mysql:8
    ports:
      - target: 3306
        published: 3306
    environment:
      - MYSQL_USER=acme
      - MYSQL_PASSWORD=acme
      - MYSQL_ROOT_PASSWORD=root
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - db-data:/var/lib/mysql
      - ./etc/infrastructure/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw

  rabbitmq:
    build:
      context: ./etc/infrastructure/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitusr
      - RABBITMQ_DEFAULT_PASS=rabbitpass
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 8083
    volumes:
      - ./etc/infrastructure/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw

volumes:
  db-data: {}
