enqueue:
    default:
        transport: '%env(resolve:ENQUEUE_DSN)%'
        client:
            traceable_producer:   true      # default value
            prefix:               acme
            separator:            .         # default value
            app_name:             platform
            router_topic:         domain-events   # default value
            router_queue:         domain-events   # default value
            router_processor:     null      # default value
            redelivered_delay_time: 0       # default value
            default_queue:        domain-events   # default value

#            traceable_producer:   true
#            prefix:               enqueue
#            separator:            .
#            app_name:             app
#            router_topic:         default
#            router_queue:         default
#            router_processor:     null
#            redelivered_delay_time: 0
#            default_queue:        default

            # The array contains driver specific options
            driver_options:       []        # default value

#        extensions:
#            doctrine_ping_connection_extension: false
#            doctrine_clear_identity_map_extension: false
#            doctrine_odm_clear_identity_map_extension: false
#            doctrine_closed_entity_manager_extension: false
#            reset_services_extension: false
#            signal_extension:     true
#            reply_extension:      true

#    some_other_transport:
#        transport: '%env(resolve:ANOTHER_ENQUEUE_DSN)%'
#        client: ~
